#
# Copyright 2015, Wink Saville
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.

libs-$(CONFIG_LIB_SEL4_MINIMAL) += libsel4minimal

libsel4minimal: kernel_elf
